version: '3'

networks: 
  php-network:
    driver: bridge

services:

  php1:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: rfaguiar/php
    container_name: php1
    #mapeando para localhost:8080
    ports:
      - "9000"
    volumes:
      - ./www:/var/www/html
    networks:
      - php-network
    depends_on: 
      - db-php
    #conecta ao containers do banco pela url http://database
    links:
      - "db-php:database"
    
  php2:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: rfaguiar/php
    container_name: php2
    #mapeando para localhost:8080
    ports:
      - "9000"
    volumes:
      - ./www:/var/www/html
    networks:
      - php-network
    depends_on: 
      - db-php
    #conecta ao containers do banco pela url http://database
    links:
      - "db-php:database"

  php3:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: rfaguiar/php
    container_name: php3
    #mapeando para localhost:8080
    ports:
      - "9000"
    volumes:
      - ./www:/var/www/html
    networks:
      - php-network
    depends_on: 
      - db-php
    #conecta ao containers do banco pela url http://database
    links:
      - "db-php:database"

  nginx:
    build: 
      dockerfile: ./Nginx/Dockerfile
      context: .
    image: rfaguiar/nginx
    container_name: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
      - ./public:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - php-network
    links:
      - php1
      - php2
      - php3
    depends_on: 
      - php1
      - php2
      - php3

  db-php:
    image: mysql:5.6
    container_name: db-php
    ports:
      - "3307:3306"
    volumes:
      - ./banco:/var/lib/mysql
    networks:
      - php-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
